const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.destroy,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Follow,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Plugins.progressbar,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Turret.Cnds.OnTargetAcquired,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.OnSignal
	];
};
self.C3_JsPropNameTable = [
	{Health: 0},
	{Collisionwithboss: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{LineOfSight: 0},
	{DestroyOutsideLayout: 0},
	{Timer: 0},
	{Player: 0},
	{Solid: 0},
	{platform: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Bullet: 0},
	{BasicGrapple: 0},
	{Derections: 0},
	{Level2: 0},
	{Follow: 0},
	{Turret: 0},
	{Sine: 0},
	{Enemy: 0},
	{EndPoint: 0},
	{Level3: 0},
	{EndPoint3: 0},
	{Boss: 0},
	{Anchor: 0},
	{Pin: 0},
	{sword: 0},
	{ProgressBar: 0},
	{Audio: 0},
	{TiledBackground: 0},
	{Pathfinding: 0},
	{MoveTo: 0},
	{fighterboss: 0},
	{ProgressBar2: 0},
	{project: 0},
	{EndText: 0},
	{BossHealth: 0},
	{Distance8: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	BasicGrapple: class extends self.ISpriteInstance {},
	Derections: class extends self.ITextInstance {},
	Level2: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EndPoint: class extends self.ISpriteInstance {},
	Level3: class extends self.ITextInstance {},
	EndPoint3: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Health: class extends self.ITextInstance {},
	sword: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	fighterboss: class extends self.ISpriteInstance {},
	ProgressBar2: class extends self.IProgressBarInstance {},
	project: class extends self.ISpriteInstance {},
	EndText: class extends self.ITextInstance {}
}